/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_algorithm;

import edu.princeton.cs.algs4.StdOut;
import edu.princeton.cs.algs4.StdRandom;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test
    public void argsTest() {
        String args[] = {"10", "100.0", "200.0"};
        // 打印N个(lo, hi)之间的随机值
            int N = Integer.parseInt(args[0]);
            double lo = Double.parseDouble(args[1]);
            double hi = Double.parseDouble(args[2]);
            for (int i = 0; i < N; i++)
            {
                double x = StdRandom.uniform(lo, hi);
                StdOut.printf("%.2f\n", x);
            }

    }
}
